/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsApiKeysRouteImport } from './routes/_authenticated/settings/api-keys'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedMasterUrusanBidangRouteImport } from './routes/_authenticated/master/urusan-bidang'
import { Route as AuthenticatedMasterUrusanRouteImport } from './routes/_authenticated/master/urusan'
import { Route as AuthenticatedMasterSkpdRouteImport } from './routes/_authenticated/master/skpd'
import { Route as AuthenticatedMasterProgramRouteImport } from './routes/_authenticated/master/program'
import { Route as AuthenticatedMasterLabelPusatRouteImport } from './routes/_authenticated/master/label-pusat'
import { Route as AuthenticatedMasterLabelProvRouteImport } from './routes/_authenticated/master/label-prov'
import { Route as AuthenticatedMasterLabelKokabRouteImport } from './routes/_authenticated/master/label-kokab'
import { Route as AuthenticatedMasterGiatSubRouteImport } from './routes/_authenticated/master/giat-sub'
import { Route as AuthenticatedMasterGiatRouteImport } from './routes/_authenticated/master/giat'
import { Route as AuthenticatedMasterDanaRouteImport } from './routes/_authenticated/master/dana'
import { Route as AuthenticatedMasterAkunRouteImport } from './routes/_authenticated/master/akun'
import { Route as AuthenticatedAnggaranSkpdRouteImport } from './routes/_authenticated/anggaran/skpd'
import { Route as AuthenticatedAnggaranBelanjaSubSubRouteImport } from './routes/_authenticated/anggaran/belanja-sub-sub'
import { Route as AuthenticatedAnggaranBelanjaSubRinciRouteImport } from './routes/_authenticated/anggaran/belanja-sub-rinci'
import { Route as AuthenticatedAnggaranBelanjaSubOutputRouteImport } from './routes/_authenticated/anggaran/belanja-sub-output'
import { Route as AuthenticatedAnggaranBelanjaSubLabelRouteImport } from './routes/_authenticated/anggaran/belanja-sub-label'
import { Route as AuthenticatedAnggaranBelanjaSubKetRouteImport } from './routes/_authenticated/anggaran/belanja-sub-ket'
import { Route as AuthenticatedAnggaranBelanjaSubDanaRouteImport } from './routes/_authenticated/anggaran/belanja-sub-dana'
import { Route as AuthenticatedAnggaranBelanjaSubRouteImport } from './routes/_authenticated/anggaran/belanja-sub'
import { Route as AuthenticatedWorkerAnggaranBelanjaSubRinciRouteImport } from './routes/_authenticated/worker/anggaran/belanja-sub-rinci'
import { Route as AuthenticatedWorkerAnggaranBelanjaSubRouteImport } from './routes/_authenticated/worker/anggaran/belanja-sub'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsApiKeysRoute =
  AuthenticatedSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedMasterUrusanBidangRoute =
  AuthenticatedMasterUrusanBidangRouteImport.update({
    id: '/master/urusan-bidang',
    path: '/master/urusan-bidang',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterUrusanRoute =
  AuthenticatedMasterUrusanRouteImport.update({
    id: '/master/urusan',
    path: '/master/urusan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterSkpdRoute = AuthenticatedMasterSkpdRouteImport.update({
  id: '/master/skpd',
  path: '/master/skpd',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMasterProgramRoute =
  AuthenticatedMasterProgramRouteImport.update({
    id: '/master/program',
    path: '/master/program',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterLabelPusatRoute =
  AuthenticatedMasterLabelPusatRouteImport.update({
    id: '/master/label-pusat',
    path: '/master/label-pusat',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterLabelProvRoute =
  AuthenticatedMasterLabelProvRouteImport.update({
    id: '/master/label-prov',
    path: '/master/label-prov',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterLabelKokabRoute =
  AuthenticatedMasterLabelKokabRouteImport.update({
    id: '/master/label-kokab',
    path: '/master/label-kokab',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterGiatSubRoute =
  AuthenticatedMasterGiatSubRouteImport.update({
    id: '/master/giat-sub',
    path: '/master/giat-sub',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterGiatRoute = AuthenticatedMasterGiatRouteImport.update({
  id: '/master/giat',
  path: '/master/giat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMasterDanaRoute = AuthenticatedMasterDanaRouteImport.update({
  id: '/master/dana',
  path: '/master/dana',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMasterAkunRoute = AuthenticatedMasterAkunRouteImport.update({
  id: '/master/akun',
  path: '/master/akun',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnggaranSkpdRoute =
  AuthenticatedAnggaranSkpdRouteImport.update({
    id: '/anggaran/skpd',
    path: '/anggaran/skpd',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnggaranBelanjaSubSubRoute =
  AuthenticatedAnggaranBelanjaSubSubRouteImport.update({
    id: '/anggaran/belanja-sub-sub',
    path: '/anggaran/belanja-sub-sub',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnggaranBelanjaSubRinciRoute =
  AuthenticatedAnggaranBelanjaSubRinciRouteImport.update({
    id: '/anggaran/belanja-sub-rinci',
    path: '/anggaran/belanja-sub-rinci',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnggaranBelanjaSubOutputRoute =
  AuthenticatedAnggaranBelanjaSubOutputRouteImport.update({
    id: '/anggaran/belanja-sub-output',
    path: '/anggaran/belanja-sub-output',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnggaranBelanjaSubLabelRoute =
  AuthenticatedAnggaranBelanjaSubLabelRouteImport.update({
    id: '/anggaran/belanja-sub-label',
    path: '/anggaran/belanja-sub-label',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnggaranBelanjaSubKetRoute =
  AuthenticatedAnggaranBelanjaSubKetRouteImport.update({
    id: '/anggaran/belanja-sub-ket',
    path: '/anggaran/belanja-sub-ket',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnggaranBelanjaSubDanaRoute =
  AuthenticatedAnggaranBelanjaSubDanaRouteImport.update({
    id: '/anggaran/belanja-sub-dana',
    path: '/anggaran/belanja-sub-dana',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAnggaranBelanjaSubRoute =
  AuthenticatedAnggaranBelanjaSubRouteImport.update({
    id: '/anggaran/belanja-sub',
    path: '/anggaran/belanja-sub',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkerAnggaranBelanjaSubRinciRoute =
  AuthenticatedWorkerAnggaranBelanjaSubRinciRouteImport.update({
    id: '/worker/anggaran/belanja-sub-rinci',
    path: '/worker/anggaran/belanja-sub-rinci',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkerAnggaranBelanjaSubRoute =
  AuthenticatedWorkerAnggaranBelanjaSubRouteImport.update({
    id: '/worker/anggaran/belanja-sub',
    path: '/worker/anggaran/belanja-sub',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/about': typeof AuthenticatedAboutRoute
  '/anggaran/belanja-sub': typeof AuthenticatedAnggaranBelanjaSubRoute
  '/anggaran/belanja-sub-dana': typeof AuthenticatedAnggaranBelanjaSubDanaRoute
  '/anggaran/belanja-sub-ket': typeof AuthenticatedAnggaranBelanjaSubKetRoute
  '/anggaran/belanja-sub-label': typeof AuthenticatedAnggaranBelanjaSubLabelRoute
  '/anggaran/belanja-sub-output': typeof AuthenticatedAnggaranBelanjaSubOutputRoute
  '/anggaran/belanja-sub-rinci': typeof AuthenticatedAnggaranBelanjaSubRinciRoute
  '/anggaran/belanja-sub-sub': typeof AuthenticatedAnggaranBelanjaSubSubRoute
  '/anggaran/skpd': typeof AuthenticatedAnggaranSkpdRoute
  '/master/akun': typeof AuthenticatedMasterAkunRoute
  '/master/dana': typeof AuthenticatedMasterDanaRoute
  '/master/giat': typeof AuthenticatedMasterGiatRoute
  '/master/giat-sub': typeof AuthenticatedMasterGiatSubRoute
  '/master/label-kokab': typeof AuthenticatedMasterLabelKokabRoute
  '/master/label-prov': typeof AuthenticatedMasterLabelProvRoute
  '/master/label-pusat': typeof AuthenticatedMasterLabelPusatRoute
  '/master/program': typeof AuthenticatedMasterProgramRoute
  '/master/skpd': typeof AuthenticatedMasterSkpdRoute
  '/master/urusan': typeof AuthenticatedMasterUrusanRoute
  '/master/urusan-bidang': typeof AuthenticatedMasterUrusanBidangRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/worker/anggaran/belanja-sub': typeof AuthenticatedWorkerAnggaranBelanjaSubRoute
  '/worker/anggaran/belanja-sub-rinci': typeof AuthenticatedWorkerAnggaranBelanjaSubRinciRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/about': typeof AuthenticatedAboutRoute
  '/': typeof AuthenticatedIndexRoute
  '/anggaran/belanja-sub': typeof AuthenticatedAnggaranBelanjaSubRoute
  '/anggaran/belanja-sub-dana': typeof AuthenticatedAnggaranBelanjaSubDanaRoute
  '/anggaran/belanja-sub-ket': typeof AuthenticatedAnggaranBelanjaSubKetRoute
  '/anggaran/belanja-sub-label': typeof AuthenticatedAnggaranBelanjaSubLabelRoute
  '/anggaran/belanja-sub-output': typeof AuthenticatedAnggaranBelanjaSubOutputRoute
  '/anggaran/belanja-sub-rinci': typeof AuthenticatedAnggaranBelanjaSubRinciRoute
  '/anggaran/belanja-sub-sub': typeof AuthenticatedAnggaranBelanjaSubSubRoute
  '/anggaran/skpd': typeof AuthenticatedAnggaranSkpdRoute
  '/master/akun': typeof AuthenticatedMasterAkunRoute
  '/master/dana': typeof AuthenticatedMasterDanaRoute
  '/master/giat': typeof AuthenticatedMasterGiatRoute
  '/master/giat-sub': typeof AuthenticatedMasterGiatSubRoute
  '/master/label-kokab': typeof AuthenticatedMasterLabelKokabRoute
  '/master/label-prov': typeof AuthenticatedMasterLabelProvRoute
  '/master/label-pusat': typeof AuthenticatedMasterLabelPusatRoute
  '/master/program': typeof AuthenticatedMasterProgramRoute
  '/master/skpd': typeof AuthenticatedMasterSkpdRoute
  '/master/urusan': typeof AuthenticatedMasterUrusanRoute
  '/master/urusan-bidang': typeof AuthenticatedMasterUrusanBidangRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/worker/anggaran/belanja-sub': typeof AuthenticatedWorkerAnggaranBelanjaSubRoute
  '/worker/anggaran/belanja-sub-rinci': typeof AuthenticatedWorkerAnggaranBelanjaSubRinciRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/anggaran/belanja-sub': typeof AuthenticatedAnggaranBelanjaSubRoute
  '/_authenticated/anggaran/belanja-sub-dana': typeof AuthenticatedAnggaranBelanjaSubDanaRoute
  '/_authenticated/anggaran/belanja-sub-ket': typeof AuthenticatedAnggaranBelanjaSubKetRoute
  '/_authenticated/anggaran/belanja-sub-label': typeof AuthenticatedAnggaranBelanjaSubLabelRoute
  '/_authenticated/anggaran/belanja-sub-output': typeof AuthenticatedAnggaranBelanjaSubOutputRoute
  '/_authenticated/anggaran/belanja-sub-rinci': typeof AuthenticatedAnggaranBelanjaSubRinciRoute
  '/_authenticated/anggaran/belanja-sub-sub': typeof AuthenticatedAnggaranBelanjaSubSubRoute
  '/_authenticated/anggaran/skpd': typeof AuthenticatedAnggaranSkpdRoute
  '/_authenticated/master/akun': typeof AuthenticatedMasterAkunRoute
  '/_authenticated/master/dana': typeof AuthenticatedMasterDanaRoute
  '/_authenticated/master/giat': typeof AuthenticatedMasterGiatRoute
  '/_authenticated/master/giat-sub': typeof AuthenticatedMasterGiatSubRoute
  '/_authenticated/master/label-kokab': typeof AuthenticatedMasterLabelKokabRoute
  '/_authenticated/master/label-prov': typeof AuthenticatedMasterLabelProvRoute
  '/_authenticated/master/label-pusat': typeof AuthenticatedMasterLabelPusatRoute
  '/_authenticated/master/program': typeof AuthenticatedMasterProgramRoute
  '/_authenticated/master/skpd': typeof AuthenticatedMasterSkpdRoute
  '/_authenticated/master/urusan': typeof AuthenticatedMasterUrusanRoute
  '/_authenticated/master/urusan-bidang': typeof AuthenticatedMasterUrusanBidangRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/worker/anggaran/belanja-sub': typeof AuthenticatedWorkerAnggaranBelanjaSubRoute
  '/_authenticated/worker/anggaran/belanja-sub-rinci': typeof AuthenticatedWorkerAnggaranBelanjaSubRinciRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/login'
    | '/register'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/about'
    | '/anggaran/belanja-sub'
    | '/anggaran/belanja-sub-dana'
    | '/anggaran/belanja-sub-ket'
    | '/anggaran/belanja-sub-label'
    | '/anggaran/belanja-sub-output'
    | '/anggaran/belanja-sub-rinci'
    | '/anggaran/belanja-sub-sub'
    | '/anggaran/skpd'
    | '/master/akun'
    | '/master/dana'
    | '/master/giat'
    | '/master/giat-sub'
    | '/master/label-kokab'
    | '/master/label-prov'
    | '/master/label-pusat'
    | '/master/program'
    | '/master/skpd'
    | '/master/urusan'
    | '/master/urusan-bidang'
    | '/settings/account'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings/'
    | '/users/'
    | '/worker/anggaran/belanja-sub'
    | '/worker/anggaran/belanja-sub-rinci'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/about'
    | '/'
    | '/anggaran/belanja-sub'
    | '/anggaran/belanja-sub-dana'
    | '/anggaran/belanja-sub-ket'
    | '/anggaran/belanja-sub-label'
    | '/anggaran/belanja-sub-output'
    | '/anggaran/belanja-sub-rinci'
    | '/anggaran/belanja-sub-sub'
    | '/anggaran/skpd'
    | '/master/akun'
    | '/master/dana'
    | '/master/giat'
    | '/master/giat-sub'
    | '/master/label-kokab'
    | '/master/label-prov'
    | '/master/label-pusat'
    | '/master/program'
    | '/master/skpd'
    | '/master/urusan'
    | '/master/urusan-bidang'
    | '/settings/account'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings'
    | '/users'
    | '/worker/anggaran/belanja-sub'
    | '/worker/anggaran/belanja-sub-rinci'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/about'
    | '/_authenticated/'
    | '/_authenticated/anggaran/belanja-sub'
    | '/_authenticated/anggaran/belanja-sub-dana'
    | '/_authenticated/anggaran/belanja-sub-ket'
    | '/_authenticated/anggaran/belanja-sub-label'
    | '/_authenticated/anggaran/belanja-sub-output'
    | '/_authenticated/anggaran/belanja-sub-rinci'
    | '/_authenticated/anggaran/belanja-sub-sub'
    | '/_authenticated/anggaran/skpd'
    | '/_authenticated/master/akun'
    | '/_authenticated/master/dana'
    | '/_authenticated/master/giat'
    | '/_authenticated/master/giat-sub'
    | '/_authenticated/master/label-kokab'
    | '/_authenticated/master/label-prov'
    | '/_authenticated/master/label-pusat'
    | '/_authenticated/master/program'
    | '/_authenticated/master/skpd'
    | '/_authenticated/master/urusan'
    | '/_authenticated/master/urusan-bidang'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/api-keys'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/'
    | '/_authenticated/users/'
    | '/_authenticated/worker/anggaran/belanja-sub'
    | '/_authenticated/worker/anggaran/belanja-sub-rinci'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/api-keys': {
      id: '/_authenticated/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/master/urusan-bidang': {
      id: '/_authenticated/master/urusan-bidang'
      path: '/master/urusan-bidang'
      fullPath: '/master/urusan-bidang'
      preLoaderRoute: typeof AuthenticatedMasterUrusanBidangRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/urusan': {
      id: '/_authenticated/master/urusan'
      path: '/master/urusan'
      fullPath: '/master/urusan'
      preLoaderRoute: typeof AuthenticatedMasterUrusanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/skpd': {
      id: '/_authenticated/master/skpd'
      path: '/master/skpd'
      fullPath: '/master/skpd'
      preLoaderRoute: typeof AuthenticatedMasterSkpdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/program': {
      id: '/_authenticated/master/program'
      path: '/master/program'
      fullPath: '/master/program'
      preLoaderRoute: typeof AuthenticatedMasterProgramRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/label-pusat': {
      id: '/_authenticated/master/label-pusat'
      path: '/master/label-pusat'
      fullPath: '/master/label-pusat'
      preLoaderRoute: typeof AuthenticatedMasterLabelPusatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/label-prov': {
      id: '/_authenticated/master/label-prov'
      path: '/master/label-prov'
      fullPath: '/master/label-prov'
      preLoaderRoute: typeof AuthenticatedMasterLabelProvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/label-kokab': {
      id: '/_authenticated/master/label-kokab'
      path: '/master/label-kokab'
      fullPath: '/master/label-kokab'
      preLoaderRoute: typeof AuthenticatedMasterLabelKokabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/giat-sub': {
      id: '/_authenticated/master/giat-sub'
      path: '/master/giat-sub'
      fullPath: '/master/giat-sub'
      preLoaderRoute: typeof AuthenticatedMasterGiatSubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/giat': {
      id: '/_authenticated/master/giat'
      path: '/master/giat'
      fullPath: '/master/giat'
      preLoaderRoute: typeof AuthenticatedMasterGiatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/dana': {
      id: '/_authenticated/master/dana'
      path: '/master/dana'
      fullPath: '/master/dana'
      preLoaderRoute: typeof AuthenticatedMasterDanaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/akun': {
      id: '/_authenticated/master/akun'
      path: '/master/akun'
      fullPath: '/master/akun'
      preLoaderRoute: typeof AuthenticatedMasterAkunRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anggaran/skpd': {
      id: '/_authenticated/anggaran/skpd'
      path: '/anggaran/skpd'
      fullPath: '/anggaran/skpd'
      preLoaderRoute: typeof AuthenticatedAnggaranSkpdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anggaran/belanja-sub-sub': {
      id: '/_authenticated/anggaran/belanja-sub-sub'
      path: '/anggaran/belanja-sub-sub'
      fullPath: '/anggaran/belanja-sub-sub'
      preLoaderRoute: typeof AuthenticatedAnggaranBelanjaSubSubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anggaran/belanja-sub-rinci': {
      id: '/_authenticated/anggaran/belanja-sub-rinci'
      path: '/anggaran/belanja-sub-rinci'
      fullPath: '/anggaran/belanja-sub-rinci'
      preLoaderRoute: typeof AuthenticatedAnggaranBelanjaSubRinciRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anggaran/belanja-sub-output': {
      id: '/_authenticated/anggaran/belanja-sub-output'
      path: '/anggaran/belanja-sub-output'
      fullPath: '/anggaran/belanja-sub-output'
      preLoaderRoute: typeof AuthenticatedAnggaranBelanjaSubOutputRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anggaran/belanja-sub-label': {
      id: '/_authenticated/anggaran/belanja-sub-label'
      path: '/anggaran/belanja-sub-label'
      fullPath: '/anggaran/belanja-sub-label'
      preLoaderRoute: typeof AuthenticatedAnggaranBelanjaSubLabelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anggaran/belanja-sub-ket': {
      id: '/_authenticated/anggaran/belanja-sub-ket'
      path: '/anggaran/belanja-sub-ket'
      fullPath: '/anggaran/belanja-sub-ket'
      preLoaderRoute: typeof AuthenticatedAnggaranBelanjaSubKetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anggaran/belanja-sub-dana': {
      id: '/_authenticated/anggaran/belanja-sub-dana'
      path: '/anggaran/belanja-sub-dana'
      fullPath: '/anggaran/belanja-sub-dana'
      preLoaderRoute: typeof AuthenticatedAnggaranBelanjaSubDanaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/anggaran/belanja-sub': {
      id: '/_authenticated/anggaran/belanja-sub'
      path: '/anggaran/belanja-sub'
      fullPath: '/anggaran/belanja-sub'
      preLoaderRoute: typeof AuthenticatedAnggaranBelanjaSubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker/anggaran/belanja-sub-rinci': {
      id: '/_authenticated/worker/anggaran/belanja-sub-rinci'
      path: '/worker/anggaran/belanja-sub-rinci'
      fullPath: '/worker/anggaran/belanja-sub-rinci'
      preLoaderRoute: typeof AuthenticatedWorkerAnggaranBelanjaSubRinciRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker/anggaran/belanja-sub': {
      id: '/_authenticated/worker/anggaran/belanja-sub'
      path: '/worker/anggaran/belanja-sub'
      fullPath: '/worker/anggaran/belanja-sub'
      preLoaderRoute: typeof AuthenticatedWorkerAnggaranBelanjaSubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsApiKeysRoute: typeof AuthenticatedSettingsApiKeysRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsApiKeysRoute: AuthenticatedSettingsApiKeysRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAnggaranBelanjaSubRoute: typeof AuthenticatedAnggaranBelanjaSubRoute
  AuthenticatedAnggaranBelanjaSubDanaRoute: typeof AuthenticatedAnggaranBelanjaSubDanaRoute
  AuthenticatedAnggaranBelanjaSubKetRoute: typeof AuthenticatedAnggaranBelanjaSubKetRoute
  AuthenticatedAnggaranBelanjaSubLabelRoute: typeof AuthenticatedAnggaranBelanjaSubLabelRoute
  AuthenticatedAnggaranBelanjaSubOutputRoute: typeof AuthenticatedAnggaranBelanjaSubOutputRoute
  AuthenticatedAnggaranBelanjaSubRinciRoute: typeof AuthenticatedAnggaranBelanjaSubRinciRoute
  AuthenticatedAnggaranBelanjaSubSubRoute: typeof AuthenticatedAnggaranBelanjaSubSubRoute
  AuthenticatedAnggaranSkpdRoute: typeof AuthenticatedAnggaranSkpdRoute
  AuthenticatedMasterAkunRoute: typeof AuthenticatedMasterAkunRoute
  AuthenticatedMasterDanaRoute: typeof AuthenticatedMasterDanaRoute
  AuthenticatedMasterGiatRoute: typeof AuthenticatedMasterGiatRoute
  AuthenticatedMasterGiatSubRoute: typeof AuthenticatedMasterGiatSubRoute
  AuthenticatedMasterLabelKokabRoute: typeof AuthenticatedMasterLabelKokabRoute
  AuthenticatedMasterLabelProvRoute: typeof AuthenticatedMasterLabelProvRoute
  AuthenticatedMasterLabelPusatRoute: typeof AuthenticatedMasterLabelPusatRoute
  AuthenticatedMasterProgramRoute: typeof AuthenticatedMasterProgramRoute
  AuthenticatedMasterSkpdRoute: typeof AuthenticatedMasterSkpdRoute
  AuthenticatedMasterUrusanRoute: typeof AuthenticatedMasterUrusanRoute
  AuthenticatedMasterUrusanBidangRoute: typeof AuthenticatedMasterUrusanBidangRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedWorkerAnggaranBelanjaSubRoute: typeof AuthenticatedWorkerAnggaranBelanjaSubRoute
  AuthenticatedWorkerAnggaranBelanjaSubRinciRoute: typeof AuthenticatedWorkerAnggaranBelanjaSubRinciRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAnggaranBelanjaSubRoute: AuthenticatedAnggaranBelanjaSubRoute,
  AuthenticatedAnggaranBelanjaSubDanaRoute:
    AuthenticatedAnggaranBelanjaSubDanaRoute,
  AuthenticatedAnggaranBelanjaSubKetRoute:
    AuthenticatedAnggaranBelanjaSubKetRoute,
  AuthenticatedAnggaranBelanjaSubLabelRoute:
    AuthenticatedAnggaranBelanjaSubLabelRoute,
  AuthenticatedAnggaranBelanjaSubOutputRoute:
    AuthenticatedAnggaranBelanjaSubOutputRoute,
  AuthenticatedAnggaranBelanjaSubRinciRoute:
    AuthenticatedAnggaranBelanjaSubRinciRoute,
  AuthenticatedAnggaranBelanjaSubSubRoute:
    AuthenticatedAnggaranBelanjaSubSubRoute,
  AuthenticatedAnggaranSkpdRoute: AuthenticatedAnggaranSkpdRoute,
  AuthenticatedMasterAkunRoute: AuthenticatedMasterAkunRoute,
  AuthenticatedMasterDanaRoute: AuthenticatedMasterDanaRoute,
  AuthenticatedMasterGiatRoute: AuthenticatedMasterGiatRoute,
  AuthenticatedMasterGiatSubRoute: AuthenticatedMasterGiatSubRoute,
  AuthenticatedMasterLabelKokabRoute: AuthenticatedMasterLabelKokabRoute,
  AuthenticatedMasterLabelProvRoute: AuthenticatedMasterLabelProvRoute,
  AuthenticatedMasterLabelPusatRoute: AuthenticatedMasterLabelPusatRoute,
  AuthenticatedMasterProgramRoute: AuthenticatedMasterProgramRoute,
  AuthenticatedMasterSkpdRoute: AuthenticatedMasterSkpdRoute,
  AuthenticatedMasterUrusanRoute: AuthenticatedMasterUrusanRoute,
  AuthenticatedMasterUrusanBidangRoute: AuthenticatedMasterUrusanBidangRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedWorkerAnggaranBelanjaSubRoute:
    AuthenticatedWorkerAnggaranBelanjaSubRoute,
  AuthenticatedWorkerAnggaranBelanjaSubRinciRoute:
    AuthenticatedWorkerAnggaranBelanjaSubRinciRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
