/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsApiKeysRouteImport } from './routes/_authenticated/settings/api-keys'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedWorkerAnggaranBelanjaSubRinciRouteImport } from './routes/_authenticated/worker/anggaran/belanja-sub-rinci'
import { Route as AuthenticatedWorkerAnggaranBelanjaSubRouteImport } from './routes/_authenticated/worker/anggaran/belanja-sub'
import { Route as AuthenticatedGetterMasterUrusanBidangRouteImport } from './routes/_authenticated/getter/master/urusan-bidang'
import { Route as AuthenticatedGetterMasterUrusanRouteImport } from './routes/_authenticated/getter/master/urusan'
import { Route as AuthenticatedGetterMasterSkpdRouteImport } from './routes/_authenticated/getter/master/skpd'
import { Route as AuthenticatedGetterMasterProgramRouteImport } from './routes/_authenticated/getter/master/program'
import { Route as AuthenticatedGetterMasterLabelPusatRouteImport } from './routes/_authenticated/getter/master/label-pusat'
import { Route as AuthenticatedGetterMasterLabelProvRouteImport } from './routes/_authenticated/getter/master/label-prov'
import { Route as AuthenticatedGetterMasterLabelKokabRouteImport } from './routes/_authenticated/getter/master/label-kokab'
import { Route as AuthenticatedGetterMasterGiatSubRouteImport } from './routes/_authenticated/getter/master/giat-sub'
import { Route as AuthenticatedGetterMasterGiatRouteImport } from './routes/_authenticated/getter/master/giat'
import { Route as AuthenticatedGetterMasterDanaRouteImport } from './routes/_authenticated/getter/master/dana'
import { Route as AuthenticatedGetterMasterAkunRouteImport } from './routes/_authenticated/getter/master/akun'
import { Route as AuthenticatedGetterAnggaranSkpdRouteImport } from './routes/_authenticated/getter/anggaran/skpd'
import { Route as AuthenticatedGetterAnggaranBelanjaSubSubRouteImport } from './routes/_authenticated/getter/anggaran/belanja-sub-sub'
import { Route as AuthenticatedGetterAnggaranBelanjaSubRinciRouteImport } from './routes/_authenticated/getter/anggaran/belanja-sub-rinci'
import { Route as AuthenticatedGetterAnggaranBelanjaSubOutputRouteImport } from './routes/_authenticated/getter/anggaran/belanja-sub-output'
import { Route as AuthenticatedGetterAnggaranBelanjaSubLabelRouteImport } from './routes/_authenticated/getter/anggaran/belanja-sub-label'
import { Route as AuthenticatedGetterAnggaranBelanjaSubKetRouteImport } from './routes/_authenticated/getter/anggaran/belanja-sub-ket'
import { Route as AuthenticatedGetterAnggaranBelanjaSubDanaRouteImport } from './routes/_authenticated/getter/anggaran/belanja-sub-dana'
import { Route as AuthenticatedGetterAnggaranBelanjaSubRouteImport } from './routes/_authenticated/getter/anggaran/belanja-sub'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsApiKeysRoute =
  AuthenticatedSettingsApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedWorkerAnggaranBelanjaSubRinciRoute =
  AuthenticatedWorkerAnggaranBelanjaSubRinciRouteImport.update({
    id: '/worker/anggaran/belanja-sub-rinci',
    path: '/worker/anggaran/belanja-sub-rinci',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkerAnggaranBelanjaSubRoute =
  AuthenticatedWorkerAnggaranBelanjaSubRouteImport.update({
    id: '/worker/anggaran/belanja-sub',
    path: '/worker/anggaran/belanja-sub',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGetterMasterUrusanBidangRoute =
  AuthenticatedGetterMasterUrusanBidangRouteImport.update({
    id: '/getter/master/urusan-bidang',
    path: '/getter/master/urusan-bidang',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGetterMasterUrusanRoute =
  AuthenticatedGetterMasterUrusanRouteImport.update({
    id: '/getter/master/urusan',
    path: '/getter/master/urusan',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGetterMasterSkpdRoute =
  AuthenticatedGetterMasterSkpdRouteImport.update({
    id: '/getter/master/skpd',
    path: '/getter/master/skpd',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGetterMasterProgramRoute =
  AuthenticatedGetterMasterProgramRouteImport.update({
    id: '/getter/master/program',
    path: '/getter/master/program',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGetterMasterLabelPusatRoute =
  AuthenticatedGetterMasterLabelPusatRouteImport.update({
    id: '/getter/master/label-pusat',
    path: '/getter/master/label-pusat',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGetterMasterLabelProvRoute =
  AuthenticatedGetterMasterLabelProvRouteImport.update({
    id: '/getter/master/label-prov',
    path: '/getter/master/label-prov',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGetterMasterLabelKokabRoute =
  AuthenticatedGetterMasterLabelKokabRouteImport.update({
    id: '/getter/master/label-kokab',
    path: '/getter/master/label-kokab',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGetterMasterGiatSubRoute =
  AuthenticatedGetterMasterGiatSubRouteImport.update({
    id: '/getter/master/giat-sub',
    path: '/getter/master/giat-sub',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGetterMasterGiatRoute =
  AuthenticatedGetterMasterGiatRouteImport.update({
    id: '/getter/master/giat',
    path: '/getter/master/giat',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGetterMasterDanaRoute =
  AuthenticatedGetterMasterDanaRouteImport.update({
    id: '/getter/master/dana',
    path: '/getter/master/dana',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGetterMasterAkunRoute =
  AuthenticatedGetterMasterAkunRouteImport.update({
    id: '/getter/master/akun',
    path: '/getter/master/akun',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGetterAnggaranSkpdRoute =
  AuthenticatedGetterAnggaranSkpdRouteImport.update({
    id: '/getter/anggaran/skpd',
    path: '/getter/anggaran/skpd',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGetterAnggaranBelanjaSubSubRoute =
  AuthenticatedGetterAnggaranBelanjaSubSubRouteImport.update({
    id: '/getter/anggaran/belanja-sub-sub',
    path: '/getter/anggaran/belanja-sub-sub',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGetterAnggaranBelanjaSubRinciRoute =
  AuthenticatedGetterAnggaranBelanjaSubRinciRouteImport.update({
    id: '/getter/anggaran/belanja-sub-rinci',
    path: '/getter/anggaran/belanja-sub-rinci',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGetterAnggaranBelanjaSubOutputRoute =
  AuthenticatedGetterAnggaranBelanjaSubOutputRouteImport.update({
    id: '/getter/anggaran/belanja-sub-output',
    path: '/getter/anggaran/belanja-sub-output',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGetterAnggaranBelanjaSubLabelRoute =
  AuthenticatedGetterAnggaranBelanjaSubLabelRouteImport.update({
    id: '/getter/anggaran/belanja-sub-label',
    path: '/getter/anggaran/belanja-sub-label',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGetterAnggaranBelanjaSubKetRoute =
  AuthenticatedGetterAnggaranBelanjaSubKetRouteImport.update({
    id: '/getter/anggaran/belanja-sub-ket',
    path: '/getter/anggaran/belanja-sub-ket',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGetterAnggaranBelanjaSubDanaRoute =
  AuthenticatedGetterAnggaranBelanjaSubDanaRouteImport.update({
    id: '/getter/anggaran/belanja-sub-dana',
    path: '/getter/anggaran/belanja-sub-dana',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGetterAnggaranBelanjaSubRoute =
  AuthenticatedGetterAnggaranBelanjaSubRouteImport.update({
    id: '/getter/anggaran/belanja-sub',
    path: '/getter/anggaran/belanja-sub',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/about': typeof AuthenticatedAboutRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/getter/anggaran/belanja-sub': typeof AuthenticatedGetterAnggaranBelanjaSubRoute
  '/getter/anggaran/belanja-sub-dana': typeof AuthenticatedGetterAnggaranBelanjaSubDanaRoute
  '/getter/anggaran/belanja-sub-ket': typeof AuthenticatedGetterAnggaranBelanjaSubKetRoute
  '/getter/anggaran/belanja-sub-label': typeof AuthenticatedGetterAnggaranBelanjaSubLabelRoute
  '/getter/anggaran/belanja-sub-output': typeof AuthenticatedGetterAnggaranBelanjaSubOutputRoute
  '/getter/anggaran/belanja-sub-rinci': typeof AuthenticatedGetterAnggaranBelanjaSubRinciRoute
  '/getter/anggaran/belanja-sub-sub': typeof AuthenticatedGetterAnggaranBelanjaSubSubRoute
  '/getter/anggaran/skpd': typeof AuthenticatedGetterAnggaranSkpdRoute
  '/getter/master/akun': typeof AuthenticatedGetterMasterAkunRoute
  '/getter/master/dana': typeof AuthenticatedGetterMasterDanaRoute
  '/getter/master/giat': typeof AuthenticatedGetterMasterGiatRoute
  '/getter/master/giat-sub': typeof AuthenticatedGetterMasterGiatSubRoute
  '/getter/master/label-kokab': typeof AuthenticatedGetterMasterLabelKokabRoute
  '/getter/master/label-prov': typeof AuthenticatedGetterMasterLabelProvRoute
  '/getter/master/label-pusat': typeof AuthenticatedGetterMasterLabelPusatRoute
  '/getter/master/program': typeof AuthenticatedGetterMasterProgramRoute
  '/getter/master/skpd': typeof AuthenticatedGetterMasterSkpdRoute
  '/getter/master/urusan': typeof AuthenticatedGetterMasterUrusanRoute
  '/getter/master/urusan-bidang': typeof AuthenticatedGetterMasterUrusanBidangRoute
  '/worker/anggaran/belanja-sub': typeof AuthenticatedWorkerAnggaranBelanjaSubRoute
  '/worker/anggaran/belanja-sub-rinci': typeof AuthenticatedWorkerAnggaranBelanjaSubRinciRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/about': typeof AuthenticatedAboutRoute
  '/': typeof AuthenticatedIndexRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/getter/anggaran/belanja-sub': typeof AuthenticatedGetterAnggaranBelanjaSubRoute
  '/getter/anggaran/belanja-sub-dana': typeof AuthenticatedGetterAnggaranBelanjaSubDanaRoute
  '/getter/anggaran/belanja-sub-ket': typeof AuthenticatedGetterAnggaranBelanjaSubKetRoute
  '/getter/anggaran/belanja-sub-label': typeof AuthenticatedGetterAnggaranBelanjaSubLabelRoute
  '/getter/anggaran/belanja-sub-output': typeof AuthenticatedGetterAnggaranBelanjaSubOutputRoute
  '/getter/anggaran/belanja-sub-rinci': typeof AuthenticatedGetterAnggaranBelanjaSubRinciRoute
  '/getter/anggaran/belanja-sub-sub': typeof AuthenticatedGetterAnggaranBelanjaSubSubRoute
  '/getter/anggaran/skpd': typeof AuthenticatedGetterAnggaranSkpdRoute
  '/getter/master/akun': typeof AuthenticatedGetterMasterAkunRoute
  '/getter/master/dana': typeof AuthenticatedGetterMasterDanaRoute
  '/getter/master/giat': typeof AuthenticatedGetterMasterGiatRoute
  '/getter/master/giat-sub': typeof AuthenticatedGetterMasterGiatSubRoute
  '/getter/master/label-kokab': typeof AuthenticatedGetterMasterLabelKokabRoute
  '/getter/master/label-prov': typeof AuthenticatedGetterMasterLabelProvRoute
  '/getter/master/label-pusat': typeof AuthenticatedGetterMasterLabelPusatRoute
  '/getter/master/program': typeof AuthenticatedGetterMasterProgramRoute
  '/getter/master/skpd': typeof AuthenticatedGetterMasterSkpdRoute
  '/getter/master/urusan': typeof AuthenticatedGetterMasterUrusanRoute
  '/getter/master/urusan-bidang': typeof AuthenticatedGetterMasterUrusanBidangRoute
  '/worker/anggaran/belanja-sub': typeof AuthenticatedWorkerAnggaranBelanjaSubRoute
  '/worker/anggaran/belanja-sub-rinci': typeof AuthenticatedWorkerAnggaranBelanjaSubRinciRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/api-keys': typeof AuthenticatedSettingsApiKeysRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/getter/anggaran/belanja-sub': typeof AuthenticatedGetterAnggaranBelanjaSubRoute
  '/_authenticated/getter/anggaran/belanja-sub-dana': typeof AuthenticatedGetterAnggaranBelanjaSubDanaRoute
  '/_authenticated/getter/anggaran/belanja-sub-ket': typeof AuthenticatedGetterAnggaranBelanjaSubKetRoute
  '/_authenticated/getter/anggaran/belanja-sub-label': typeof AuthenticatedGetterAnggaranBelanjaSubLabelRoute
  '/_authenticated/getter/anggaran/belanja-sub-output': typeof AuthenticatedGetterAnggaranBelanjaSubOutputRoute
  '/_authenticated/getter/anggaran/belanja-sub-rinci': typeof AuthenticatedGetterAnggaranBelanjaSubRinciRoute
  '/_authenticated/getter/anggaran/belanja-sub-sub': typeof AuthenticatedGetterAnggaranBelanjaSubSubRoute
  '/_authenticated/getter/anggaran/skpd': typeof AuthenticatedGetterAnggaranSkpdRoute
  '/_authenticated/getter/master/akun': typeof AuthenticatedGetterMasterAkunRoute
  '/_authenticated/getter/master/dana': typeof AuthenticatedGetterMasterDanaRoute
  '/_authenticated/getter/master/giat': typeof AuthenticatedGetterMasterGiatRoute
  '/_authenticated/getter/master/giat-sub': typeof AuthenticatedGetterMasterGiatSubRoute
  '/_authenticated/getter/master/label-kokab': typeof AuthenticatedGetterMasterLabelKokabRoute
  '/_authenticated/getter/master/label-prov': typeof AuthenticatedGetterMasterLabelProvRoute
  '/_authenticated/getter/master/label-pusat': typeof AuthenticatedGetterMasterLabelPusatRoute
  '/_authenticated/getter/master/program': typeof AuthenticatedGetterMasterProgramRoute
  '/_authenticated/getter/master/skpd': typeof AuthenticatedGetterMasterSkpdRoute
  '/_authenticated/getter/master/urusan': typeof AuthenticatedGetterMasterUrusanRoute
  '/_authenticated/getter/master/urusan-bidang': typeof AuthenticatedGetterMasterUrusanBidangRoute
  '/_authenticated/worker/anggaran/belanja-sub': typeof AuthenticatedWorkerAnggaranBelanjaSubRoute
  '/_authenticated/worker/anggaran/belanja-sub-rinci': typeof AuthenticatedWorkerAnggaranBelanjaSubRinciRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/login'
    | '/register'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/about'
    | '/settings/account'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings/'
    | '/users/'
    | '/getter/anggaran/belanja-sub'
    | '/getter/anggaran/belanja-sub-dana'
    | '/getter/anggaran/belanja-sub-ket'
    | '/getter/anggaran/belanja-sub-label'
    | '/getter/anggaran/belanja-sub-output'
    | '/getter/anggaran/belanja-sub-rinci'
    | '/getter/anggaran/belanja-sub-sub'
    | '/getter/anggaran/skpd'
    | '/getter/master/akun'
    | '/getter/master/dana'
    | '/getter/master/giat'
    | '/getter/master/giat-sub'
    | '/getter/master/label-kokab'
    | '/getter/master/label-prov'
    | '/getter/master/label-pusat'
    | '/getter/master/program'
    | '/getter/master/skpd'
    | '/getter/master/urusan'
    | '/getter/master/urusan-bidang'
    | '/worker/anggaran/belanja-sub'
    | '/worker/anggaran/belanja-sub-rinci'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/about'
    | '/'
    | '/settings/account'
    | '/settings/api-keys'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings'
    | '/users'
    | '/getter/anggaran/belanja-sub'
    | '/getter/anggaran/belanja-sub-dana'
    | '/getter/anggaran/belanja-sub-ket'
    | '/getter/anggaran/belanja-sub-label'
    | '/getter/anggaran/belanja-sub-output'
    | '/getter/anggaran/belanja-sub-rinci'
    | '/getter/anggaran/belanja-sub-sub'
    | '/getter/anggaran/skpd'
    | '/getter/master/akun'
    | '/getter/master/dana'
    | '/getter/master/giat'
    | '/getter/master/giat-sub'
    | '/getter/master/label-kokab'
    | '/getter/master/label-prov'
    | '/getter/master/label-pusat'
    | '/getter/master/program'
    | '/getter/master/skpd'
    | '/getter/master/urusan'
    | '/getter/master/urusan-bidang'
    | '/worker/anggaran/belanja-sub'
    | '/worker/anggaran/belanja-sub-rinci'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/about'
    | '/_authenticated/'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/api-keys'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/'
    | '/_authenticated/users/'
    | '/_authenticated/getter/anggaran/belanja-sub'
    | '/_authenticated/getter/anggaran/belanja-sub-dana'
    | '/_authenticated/getter/anggaran/belanja-sub-ket'
    | '/_authenticated/getter/anggaran/belanja-sub-label'
    | '/_authenticated/getter/anggaran/belanja-sub-output'
    | '/_authenticated/getter/anggaran/belanja-sub-rinci'
    | '/_authenticated/getter/anggaran/belanja-sub-sub'
    | '/_authenticated/getter/anggaran/skpd'
    | '/_authenticated/getter/master/akun'
    | '/_authenticated/getter/master/dana'
    | '/_authenticated/getter/master/giat'
    | '/_authenticated/getter/master/giat-sub'
    | '/_authenticated/getter/master/label-kokab'
    | '/_authenticated/getter/master/label-prov'
    | '/_authenticated/getter/master/label-pusat'
    | '/_authenticated/getter/master/program'
    | '/_authenticated/getter/master/skpd'
    | '/_authenticated/getter/master/urusan'
    | '/_authenticated/getter/master/urusan-bidang'
    | '/_authenticated/worker/anggaran/belanja-sub'
    | '/_authenticated/worker/anggaran/belanja-sub-rinci'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/api-keys': {
      id: '/_authenticated/settings/api-keys'
      path: '/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedSettingsApiKeysRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/worker/anggaran/belanja-sub-rinci': {
      id: '/_authenticated/worker/anggaran/belanja-sub-rinci'
      path: '/worker/anggaran/belanja-sub-rinci'
      fullPath: '/worker/anggaran/belanja-sub-rinci'
      preLoaderRoute: typeof AuthenticatedWorkerAnggaranBelanjaSubRinciRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/worker/anggaran/belanja-sub': {
      id: '/_authenticated/worker/anggaran/belanja-sub'
      path: '/worker/anggaran/belanja-sub'
      fullPath: '/worker/anggaran/belanja-sub'
      preLoaderRoute: typeof AuthenticatedWorkerAnggaranBelanjaSubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/getter/master/urusan-bidang': {
      id: '/_authenticated/getter/master/urusan-bidang'
      path: '/getter/master/urusan-bidang'
      fullPath: '/getter/master/urusan-bidang'
      preLoaderRoute: typeof AuthenticatedGetterMasterUrusanBidangRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/getter/master/urusan': {
      id: '/_authenticated/getter/master/urusan'
      path: '/getter/master/urusan'
      fullPath: '/getter/master/urusan'
      preLoaderRoute: typeof AuthenticatedGetterMasterUrusanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/getter/master/skpd': {
      id: '/_authenticated/getter/master/skpd'
      path: '/getter/master/skpd'
      fullPath: '/getter/master/skpd'
      preLoaderRoute: typeof AuthenticatedGetterMasterSkpdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/getter/master/program': {
      id: '/_authenticated/getter/master/program'
      path: '/getter/master/program'
      fullPath: '/getter/master/program'
      preLoaderRoute: typeof AuthenticatedGetterMasterProgramRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/getter/master/label-pusat': {
      id: '/_authenticated/getter/master/label-pusat'
      path: '/getter/master/label-pusat'
      fullPath: '/getter/master/label-pusat'
      preLoaderRoute: typeof AuthenticatedGetterMasterLabelPusatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/getter/master/label-prov': {
      id: '/_authenticated/getter/master/label-prov'
      path: '/getter/master/label-prov'
      fullPath: '/getter/master/label-prov'
      preLoaderRoute: typeof AuthenticatedGetterMasterLabelProvRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/getter/master/label-kokab': {
      id: '/_authenticated/getter/master/label-kokab'
      path: '/getter/master/label-kokab'
      fullPath: '/getter/master/label-kokab'
      preLoaderRoute: typeof AuthenticatedGetterMasterLabelKokabRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/getter/master/giat-sub': {
      id: '/_authenticated/getter/master/giat-sub'
      path: '/getter/master/giat-sub'
      fullPath: '/getter/master/giat-sub'
      preLoaderRoute: typeof AuthenticatedGetterMasterGiatSubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/getter/master/giat': {
      id: '/_authenticated/getter/master/giat'
      path: '/getter/master/giat'
      fullPath: '/getter/master/giat'
      preLoaderRoute: typeof AuthenticatedGetterMasterGiatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/getter/master/dana': {
      id: '/_authenticated/getter/master/dana'
      path: '/getter/master/dana'
      fullPath: '/getter/master/dana'
      preLoaderRoute: typeof AuthenticatedGetterMasterDanaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/getter/master/akun': {
      id: '/_authenticated/getter/master/akun'
      path: '/getter/master/akun'
      fullPath: '/getter/master/akun'
      preLoaderRoute: typeof AuthenticatedGetterMasterAkunRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/getter/anggaran/skpd': {
      id: '/_authenticated/getter/anggaran/skpd'
      path: '/getter/anggaran/skpd'
      fullPath: '/getter/anggaran/skpd'
      preLoaderRoute: typeof AuthenticatedGetterAnggaranSkpdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/getter/anggaran/belanja-sub-sub': {
      id: '/_authenticated/getter/anggaran/belanja-sub-sub'
      path: '/getter/anggaran/belanja-sub-sub'
      fullPath: '/getter/anggaran/belanja-sub-sub'
      preLoaderRoute: typeof AuthenticatedGetterAnggaranBelanjaSubSubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/getter/anggaran/belanja-sub-rinci': {
      id: '/_authenticated/getter/anggaran/belanja-sub-rinci'
      path: '/getter/anggaran/belanja-sub-rinci'
      fullPath: '/getter/anggaran/belanja-sub-rinci'
      preLoaderRoute: typeof AuthenticatedGetterAnggaranBelanjaSubRinciRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/getter/anggaran/belanja-sub-output': {
      id: '/_authenticated/getter/anggaran/belanja-sub-output'
      path: '/getter/anggaran/belanja-sub-output'
      fullPath: '/getter/anggaran/belanja-sub-output'
      preLoaderRoute: typeof AuthenticatedGetterAnggaranBelanjaSubOutputRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/getter/anggaran/belanja-sub-label': {
      id: '/_authenticated/getter/anggaran/belanja-sub-label'
      path: '/getter/anggaran/belanja-sub-label'
      fullPath: '/getter/anggaran/belanja-sub-label'
      preLoaderRoute: typeof AuthenticatedGetterAnggaranBelanjaSubLabelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/getter/anggaran/belanja-sub-ket': {
      id: '/_authenticated/getter/anggaran/belanja-sub-ket'
      path: '/getter/anggaran/belanja-sub-ket'
      fullPath: '/getter/anggaran/belanja-sub-ket'
      preLoaderRoute: typeof AuthenticatedGetterAnggaranBelanjaSubKetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/getter/anggaran/belanja-sub-dana': {
      id: '/_authenticated/getter/anggaran/belanja-sub-dana'
      path: '/getter/anggaran/belanja-sub-dana'
      fullPath: '/getter/anggaran/belanja-sub-dana'
      preLoaderRoute: typeof AuthenticatedGetterAnggaranBelanjaSubDanaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/getter/anggaran/belanja-sub': {
      id: '/_authenticated/getter/anggaran/belanja-sub'
      path: '/getter/anggaran/belanja-sub'
      fullPath: '/getter/anggaran/belanja-sub'
      preLoaderRoute: typeof AuthenticatedGetterAnggaranBelanjaSubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsApiKeysRoute: typeof AuthenticatedSettingsApiKeysRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsApiKeysRoute: AuthenticatedSettingsApiKeysRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedGetterAnggaranBelanjaSubRoute: typeof AuthenticatedGetterAnggaranBelanjaSubRoute
  AuthenticatedGetterAnggaranBelanjaSubDanaRoute: typeof AuthenticatedGetterAnggaranBelanjaSubDanaRoute
  AuthenticatedGetterAnggaranBelanjaSubKetRoute: typeof AuthenticatedGetterAnggaranBelanjaSubKetRoute
  AuthenticatedGetterAnggaranBelanjaSubLabelRoute: typeof AuthenticatedGetterAnggaranBelanjaSubLabelRoute
  AuthenticatedGetterAnggaranBelanjaSubOutputRoute: typeof AuthenticatedGetterAnggaranBelanjaSubOutputRoute
  AuthenticatedGetterAnggaranBelanjaSubRinciRoute: typeof AuthenticatedGetterAnggaranBelanjaSubRinciRoute
  AuthenticatedGetterAnggaranBelanjaSubSubRoute: typeof AuthenticatedGetterAnggaranBelanjaSubSubRoute
  AuthenticatedGetterAnggaranSkpdRoute: typeof AuthenticatedGetterAnggaranSkpdRoute
  AuthenticatedGetterMasterAkunRoute: typeof AuthenticatedGetterMasterAkunRoute
  AuthenticatedGetterMasterDanaRoute: typeof AuthenticatedGetterMasterDanaRoute
  AuthenticatedGetterMasterGiatRoute: typeof AuthenticatedGetterMasterGiatRoute
  AuthenticatedGetterMasterGiatSubRoute: typeof AuthenticatedGetterMasterGiatSubRoute
  AuthenticatedGetterMasterLabelKokabRoute: typeof AuthenticatedGetterMasterLabelKokabRoute
  AuthenticatedGetterMasterLabelProvRoute: typeof AuthenticatedGetterMasterLabelProvRoute
  AuthenticatedGetterMasterLabelPusatRoute: typeof AuthenticatedGetterMasterLabelPusatRoute
  AuthenticatedGetterMasterProgramRoute: typeof AuthenticatedGetterMasterProgramRoute
  AuthenticatedGetterMasterSkpdRoute: typeof AuthenticatedGetterMasterSkpdRoute
  AuthenticatedGetterMasterUrusanRoute: typeof AuthenticatedGetterMasterUrusanRoute
  AuthenticatedGetterMasterUrusanBidangRoute: typeof AuthenticatedGetterMasterUrusanBidangRoute
  AuthenticatedWorkerAnggaranBelanjaSubRoute: typeof AuthenticatedWorkerAnggaranBelanjaSubRoute
  AuthenticatedWorkerAnggaranBelanjaSubRinciRoute: typeof AuthenticatedWorkerAnggaranBelanjaSubRinciRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedGetterAnggaranBelanjaSubRoute:
    AuthenticatedGetterAnggaranBelanjaSubRoute,
  AuthenticatedGetterAnggaranBelanjaSubDanaRoute:
    AuthenticatedGetterAnggaranBelanjaSubDanaRoute,
  AuthenticatedGetterAnggaranBelanjaSubKetRoute:
    AuthenticatedGetterAnggaranBelanjaSubKetRoute,
  AuthenticatedGetterAnggaranBelanjaSubLabelRoute:
    AuthenticatedGetterAnggaranBelanjaSubLabelRoute,
  AuthenticatedGetterAnggaranBelanjaSubOutputRoute:
    AuthenticatedGetterAnggaranBelanjaSubOutputRoute,
  AuthenticatedGetterAnggaranBelanjaSubRinciRoute:
    AuthenticatedGetterAnggaranBelanjaSubRinciRoute,
  AuthenticatedGetterAnggaranBelanjaSubSubRoute:
    AuthenticatedGetterAnggaranBelanjaSubSubRoute,
  AuthenticatedGetterAnggaranSkpdRoute: AuthenticatedGetterAnggaranSkpdRoute,
  AuthenticatedGetterMasterAkunRoute: AuthenticatedGetterMasterAkunRoute,
  AuthenticatedGetterMasterDanaRoute: AuthenticatedGetterMasterDanaRoute,
  AuthenticatedGetterMasterGiatRoute: AuthenticatedGetterMasterGiatRoute,
  AuthenticatedGetterMasterGiatSubRoute: AuthenticatedGetterMasterGiatSubRoute,
  AuthenticatedGetterMasterLabelKokabRoute:
    AuthenticatedGetterMasterLabelKokabRoute,
  AuthenticatedGetterMasterLabelProvRoute:
    AuthenticatedGetterMasterLabelProvRoute,
  AuthenticatedGetterMasterLabelPusatRoute:
    AuthenticatedGetterMasterLabelPusatRoute,
  AuthenticatedGetterMasterProgramRoute: AuthenticatedGetterMasterProgramRoute,
  AuthenticatedGetterMasterSkpdRoute: AuthenticatedGetterMasterSkpdRoute,
  AuthenticatedGetterMasterUrusanRoute: AuthenticatedGetterMasterUrusanRoute,
  AuthenticatedGetterMasterUrusanBidangRoute:
    AuthenticatedGetterMasterUrusanBidangRoute,
  AuthenticatedWorkerAnggaranBelanjaSubRoute:
    AuthenticatedWorkerAnggaranBelanjaSubRoute,
  AuthenticatedWorkerAnggaranBelanjaSubRinciRoute:
    AuthenticatedWorkerAnggaranBelanjaSubRinciRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
